
//REGISTER
export const REGISTER_USERNAME_EDITED = 'REGISTER_USERNAME_EDITED';
export const REGISTER_PASSWORD_EDITED = 'REGISTER_PASSWORD_EDITED';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const REGISTER_FIRST_NAME_EDITED = 'REGISTER_FIRST_NAME_EDITED';
export const REGISTER_SECOND_NAME_EDITED = 'REGISTER_SECOND_NAME_EDITED';

//LOGIN
export const LOGIN_USERNAME_EDITED = 'LOGIN_USERNAME_EDITED';
export const LOGIN_PASSWORD_EDITED = 'LOGIN_PASSWORD_EDITED';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';


//statistic

export const STATISTIC_SAVED = 'STATISTIC_SAVED';
export const GET_CURRENT_STATISTIC_VALUE = 'GET_CURRENT_STATISTIC_VALUE';



//offers

export const LOAD_IMAGE_START = "LOAD_IMAGE_START";
export const LOAD_IMAGE_SUCCESS = "LOAD_IMAGE_SUCCESS";

export const FETCH_OFFERS_START = 'FETCH_OFFERS_START';
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';
export const FETCH_OFFERS_FAILURE = 'FETCH_OFFERS_FAILURE';

export const SET_CURRENT_OFFER = 'SET_CURRENT_OFFER';

export const EDIT_OFFERS_START = 'EDIT_OFFERS_START';
export const EDIT_OFFERS_SUCCESS = 'EDIT_OFFERS_SUCCESS';
export const EDIT_OFFERS_FAILURE = 'EDIT_OFFERS_FAILURE';


export const CREATE_OFFERS_START = 'CREATE_OFFERS_START';
export const CREATE_OFFERS_SUCCESS = 'CREATE_OFFERS_SUCCESS';
export const CREATE_OFFERS_FAILURE = 'CREATE_OFFERS_FAILURE';

export const CHANGE_MODAL_STATUS = 'CHANGE_MODAL_STATUS';
export const CHANGE_CREATE_MODAL_STATUS = 'CHANGE_CREATE_MODAL_STATUS';


export const MODAL_OFFER_NAME_EDITED = 'MODAL_OFFER_NAME_EDITED';
export const MODAL_OFFER_DESCRIPTION_EDITED = 'MODAL_OFFER_DESCRIPTION_EDITED';
export const MODAL_OFFER_DISPOSABLE_EDITED = 'MODAL_OFFER_DISPOSABLE_EDITED';
export const MODAL_OFFER_PERCENTAGE_DISCOUNT_EDITED = 'MODAL_OFFER_PERCENTAGE_DISCOUNT_EDITED';
export const MODAL_OFFER_CURRENCY_DISCOUNT_EDITED = 'MODAL_OFFER_CURRENCY_DISCOUNT_EDITED';
export const MODAL_OFFER_COST_EDITED = 'MODAL_OFFER_COST_EDITED';
export const MODAL_OFFER_PERCENTAGE_DISCOUNT_LIMIT_EDITED = 'MODAL_OFFER_PERCENTAGE_DISCOUNT_LIMIT_EDITED';
export const MODAL_OFFER_CURRENCY_DISCOUNT_LIMIT_EDITED = 'MODAL_OFFER_CURRENCY_DISCOUNT_LIMIT_EDITED';
export const MODAL_OFFER_USE_BONUS_EDITED = 'MODAL_OFFER_USE_BONUS_EDITED';
export const MODAL_OFFER_GEOLOCATION_EDITED = 'MODAL_OFFER_GEOLOCATION_EDITED';

export const DISCOUNT_TYPE_CHANGED = 'DISCOUNT_TYPE_CHANGED';

export const FILE = 'FILE';

//reports

export const GAMES_FETCH_START = 'GAMES_FETCH_START';
export const GAMES_FETCH_SUCCESS = 'GAMES_FETCH_SUCCESS';
export const GAMES_FETCH_FAILURE = 'GAMES_FETCH_FAILURE';

//users

export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CHANGE_USER_MODAL_STATUS = 'CHANGE_USER_MODAL_STATUS';


//roles
export const FETCH_ROLES_SUCCESS = 'FETCH_ROLES_SUCCESS';
export const SET_CURRENT_ROLE = 'SET_CURRENT_ROLE';
