
//REGISTER
export const REGISTER_USERNAME_EDITED = 'REGISTER_USERNAME_EDITED';
export const REGISTER_PASSWORD_EDITED = 'REGISTER_PASSWORD_EDITED';
export const CREATE_USER_START = 'CREATE_USER_START';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const REGISTER_FIRST_NAME_EDITED = 'REGISTER_FIRST_NAME_EDITED';
export const REGISTER_SECOND_NAME_EDITED = 'REGISTER_SECOND_NAME_EDITED';

//LOGIN
export const LOGIN_USERNAME_EDITED = 'LOGIN_USERNAME_EDITED';
export const LOGIN_PASSWORD_EDITED = 'LOGIN_PASSWORD_EDITED';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';


//statistic

export const STATISTIC_SAVED = 'STATISTIC_SAVED';
export const GET_CURRENT_STATISTIC_VALUE = 'GET_CURRENT_STATISTIC_VALUE';